cc_binary(
    name = "naive",
    srcs = ["naive_kernel_test.cc"],
    deps = [
        "//src:gemm_lab",
    ],
)

cc_binary(
    name = "reordering",
    srcs = ["reordering_kernel_test.cc"],
    deps = [
        "//src:gemm_lab",
    ],
)

cc_binary(
    name = "tiling",
    srcs = ["tiling_kernel_test.cc"],
    deps = [
        "//src:gemm_lab",
    ],
)

cc_binary(
    name = "vectorization",
    srcs = ["vectorization_kernel_test.cc"],
    deps = [
        "//src:gemm_lab",
    ],
)

cc_binary(
    name = "array_packing",
    srcs = ["array_packing_kernel_test.cc"],
    deps = [
        "//src:gemm_lab",
    ],
)

cc_binary(
    name = "write_cache",
    srcs = ["write_cache_kernel_test.cc"],
    deps = [
        "//src:gemm_lab",
    ],
)

cc_binary(
    name = "parallel",
    srcs = ["parallel_kernel_test.cc"],
    deps = [
        "//src:gemm_lab",
    ],
)